#!/bin/bash

set -e


usage()
{
    echo "import upstream DRBD module sources into kernel tree"
    echo
    echo "usage: $(basename $0) [--help] <path-to-drbd-src>"
}


DRBDDIR=
while [ $# -gt 0 ] ; do
    case $1 in
        --help)
            usage
            exit 0
            ;;
        *)
            if [ -z "$DRBDDIR" ] ; then
                DRBDDIR=$1
            else
                echo "Unknown option or parameter \"$1\""
                echo
                usage
                exit 1
            fi
            ;;
    esac

    shift
done


# initial import
#
# FIXME: Technically, build-current is a symlink to build-$kernelversion, so
#        perhaps we should figure that out instead of using "current"?  Works
#        for now as-is, but I could see this making problems for me down the
#        road while patching multiple kernel trees.
#
cp -v $DRBDDIR/drbd/build-current/*.[ch] .
rm -v compat*.h
cp -v $DRBDDIR/drbd/Kconfig .
cp -v $DRBDDIR/drbd/build-current/Kbuild Makefile
cp -v $DRBDDIR/drbd/build-current/linux/drbd*.h ../../../include/linux/
cp -v $DRBDDIR/drbd/build-current/drbd-headers/drbd*.[ch] .
cp -v $DRBDDIR/drbd/build-current/drbd-headers/linux/*.h ../../../include/linux/
cp -v $DRBDDIR/drbd/build-current/drbd-kernel-compat/drbd_wrappers.[ch] .
cp -v $DRBDDIR/drbd/build-current/compat.h ../../../include/linux/drbd_compat.h
mkdir -p handshake
cp -v $DRBDDIR/drbd/build-current/drbd-kernel-compat/handshake/*.[ch] handshake/.
cp -v $DRBDDIR/drbd/build-current/drbd-kernel-compat/handshake/Kbuild handshake/Makefile
cp -vr $DRBDDIR/drbd/build-current/drbd-kernel-compat/net net
cp -vr $DRBDDIR/drbd/build-current/drbd-kernel-compat/uapi uapi

# Then, since we renamed compat.h->drbd_compat.h, we have to sed some changes
# into a few files:
sed -i 's|#include "compat.h"|#include <linux/drbd_compat.h>|' \
    ../../../include/linux/genl_magic_struct.h \
    drbd_wrappers.h

# And finally, we have to tweak a couple of include statements to work nicely
# now that we've actually split headers out into their propper locations:
sed -i 's|#include <kref_debug.h>|#include "kref_debug.h"|' \
    drbd_kref_debug.h

# Then generate drbd_buildtag.c w/ SHA of git tree.
SHA=$(GIT_DIR=$DRBDDIR/.git git rev-parse HEAD)
sed "s|__GIT_HASH__|$SHA|" drbd_buildtag.c.in > drbd_buildtag.c

exit 0
